// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJPLikX_usPFjTFt_C9GTeopLuP9Uxhg',
    appId: '1:706886373201:web:2619832f5ae9151070cd70',
    messagingSenderId: '706886373201',
    projectId: 'labtest-48d50',
    authDomain: 'labtest-48d50.firebaseapp.com',
    storageBucket: 'labtest-48d50.firebasestorage.app',
    measurementId: 'G-SDZXF1M9M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmy-jPnyqsSFuDQLs-qguFrNIFfkeMD0',
    appId: '1:706886373201:android:f57d16993521fddb70cd70',
    messagingSenderId: '706886373201',
    projectId: 'labtest-48d50',
    storageBucket: 'labtest-48d50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHstA2OpRtH8DI1sqK4TEEHedD2LQBILg',
    appId: '1:706886373201:ios:0ab3ee5411eb0e0870cd70',
    messagingSenderId: '706886373201',
    projectId: 'labtest-48d50',
    storageBucket: 'labtest-48d50.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHstA2OpRtH8DI1sqK4TEEHedD2LQBILg',
    appId: '1:706886373201:ios:0ab3ee5411eb0e0870cd70',
    messagingSenderId: '706886373201',
    projectId: 'labtest-48d50',
    storageBucket: 'labtest-48d50.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrJPLikX_usPFjTFt_C9GTeopLuP9Uxhg',
    appId: '1:706886373201:web:38f219167e9dc94470cd70',
    messagingSenderId: '706886373201',
    projectId: 'labtest-48d50',
    authDomain: 'labtest-48d50.firebaseapp.com',
    storageBucket: 'labtest-48d50.firebasestorage.app',
    measurementId: 'G-XCTYEDZ4M9',
  );
}
